### ISSUE TITLE
AlertDialog limited height spinner

### ISSUE THREAD

**Issue by mariooooo** [skydoves/PowerSpinner#128]
**Please complete the following information:**
- Library Version [e.g. v1.2.3]
- Affected Device(s) [Lenovo TB-7305X with Android 9.0]
 
Describe the Bug:
Problem with AlertDialog limited height
![Screenshot_2022-08-15-15-34-24-885](https://user-images.githubusercontent.com/13379774/184636114-c29f02e6-4f54-4aa9-81b0-007059580c0e.jpeg)
![Screenshot_2022-08-15-15-37-14-222](https://user-images.githubusercontent.com/13379774/184636321-d518a93f-d783-460f-a293-db7c912f63d9.jpeg)

Expected Behavior:
Like default spinner
![Screenshot_2022-08-15-15-43-08-906](https://user-images.githubusercontent.com/13379774/184637301-9366bc22-19d9-442a-a871-a46828437084.jpeg)

mb i do something wrong?

**Comment by skydoves** [comment]
Hi, this seems like a very tricky problem. The AlertDialog is a kind of window, which decides the scope of drawing view frames in the Android View system. Also, the PowerSpinner is a kind of window, so it can't oversize the parent view fundamentally. I would suggest a solution - Resize the AlertDialog as fill width and height sizes and make the background transparent. This issue is not related to the PowerSpinner, so I will close this issue for now. Thanks!
