### ISSUE TITLE
Orientation is not changing of popup window 

### ISSUE THREAD

**Issue by goswamiji0** [skydoves/PowerSpinner#60]
When i change orientation from landscape to vertical the width of the popup window remain same as landscape mode so on portrait mode its not showing well. 
Kindly suggest me how can i fix that problem with orientation

**Comment by skydoves** [comment]
Hi, @goswamiji0 
Do you mean the screen rotation?
I think the spinner popup must be destroyed when we changed the screen rotation.
Because the `PopupWindow` holds resources including `Context`, it can make memory leaks internally.
So the `PopupWindow` should be dismissed on the `onPause` or `onDismiss` lifecycle, and we should show it again `onCreate` or `onStart` lifecycle states.
